openapi: 3.0.1
info:
  title: BFF
  version: 1.0.0
paths:
  /v1/product:
    post:
      tags:
        - Product
      operationId: getProductById
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ProductRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ProductMobileResponse'
                  - $ref: '#/components/schemas/ProductDesktopResponse'
                  - $ref: '#/components/schemas/ProductOfflineResponse'
        404:
          description: not found
          content: {}
        500:
          description: server error
          content: {}
      x-codegen-request-body-name: ProductRequest
components:
  schemas:
    ProductRequest:
      required:
        - productId
        - source
      type: object
      properties:
        productId:
          type: string
        source:
          type: string
          enum:
            - MOBILE
            - DESKTOP
            - OFFLINE
    ProductMobileResponse:
      required:
        - price
        - title
      type: object
      properties:
        title:
          type: string
        price:
          type: number
        currency:
          type: string
          enum:
            - RUR
    ProductDesktopResponse:
      required:
        - price
        - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        weight:
          type: number
        height:
          type: number
        length:
          type: number
        width:
          type: number
        price:
          type: number
        currency:
          type: string
          enum:
            - RUR
    ProductOfflineResponse:
      required:
        - price
        - title
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        weight:
          type: number
        height:
          type: number
        length:
          type: number
        width:
          type: number
        price:
          type: number
        currency:
          type: string
          enum:
            - RUR
        availableStock:
          type: number
        row:
          type: number
        shell:
          type: number
