openapi: 3.0.1
info:
  title: ProductPrice
  version: 1.0.0
paths:
  /info:
    post:
      tags:
        - ProductPrice
      operationId: getProductPriceById
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ProductPriceRequest'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPriceResponse'
        404:
          description: not found
          content: {}
        500:
          description: server error
          content: {}
components:
  schemas:
    ProductPriceRequest:
      required:
        - productId
      type: object
      properties:
        productId:
          type: string
    ProductPriceResponse:
      type: object
      properties:
        price:
          type: number
        currency:
          type: string
          enum:
            - RUR
